### ISSUE TITLE
Search and (Replace + Remove)

### ISSUE THREAD

**Issue by serge73** [collective/collective.searchandreplace#13]
Not working replacement if rtext=NONE (empty replacement box)

I can't remove all occurrences of the query, only replace with a non-empty value.

A simple change in the line:100 "if replace and rtext:" to "if replace" causes an error in Unicode.

Unfortunately my experience is not sufficient to solve this problem.

I think this is a useful feature if implemented.

**Comment by mauritsvanrees** [comment]
I have released 6.0.3 with a fix for this.
