### ISSUE TITLE
Restrict searching and replacing to portal_type instead of interface

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.searchandreplace#25]
Since version 6, content types need to implement the `ISearchReplaceable` marker interface, otherwise we will not search and replace in them. Problem: when this is activated on a new content type (by enabling the dexterity behavior or for Archetypes add some zcml) the existing content is still not searched. You need to reindex the `object_provides` index. I don't like that.

Also, I would like to be able to set the enabled types in one control panel, and not have to write zcml.

Proposal:
- Create a control panel where we can set the supported types. An In-Out widget is probably best for this, so you can easily select them. In an upgrade we could try to be smart and try to determine which types to enable by default. Or we enable a few standard ones.
- On that control panel, also have a boolean option 'restrict types'. Default False: the settings in the In-Out widget are ignored and all types are searched. Then we are back to what happened before version 6.
- Save the settings in plone.app.registry.
- Update the searchandreplace utility to no longer restrict the search on the `ISearchReplaceable` interface, but on the given portal_types.
- Cleanup the dexterity behavior and other code needed for the way we are doing it now. Make sure that this does not break existing sites: I am not sure if removing the behavior from the code gives errors when there are still types that use this behavior. An upgrade step is probably needed and we may need to keep the interface around for a while.

I can do this.

@Gagaro What do you think of this? You added this in pull request #4. Would the new way fit your use cases?

**Comment by Gagaro** [comment]
Yes this looks like a better way to do it (especially for Archetypes). My need was just to only search on some content types, so this would also works.

I don't know either how the existing content would behave without the behaviour. We should deprecate it and remove it in a later version.

**Comment by mauritsvanrees** [comment]
Will be in 7.0.
