### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by serge73** [collective/collective.searchandreplace#33]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

Additional product is only for sites in the English language.
I can't search in Russian, I think in other non-English too.

**Comment by Gagaro** [comment]
I'm using it on a French website and have no issue (with "é" for example).

**Comment by serge73** [comment]
I installed a fresh copy of Plone-5.0.5-UnifiedInstaller on a Debian

./install.sh standalone --password=12345 --target=/usr/local/Plone505test

added collective.searchandreplace, five.formlib to "eggs ="
Set French by default.
Moved to the main page 
Perform a search for "trouvé"
The resul:
............
 Module collective.searchandreplace.browser.searchreplacetable, line 40, in getItems
  Module collective.searchandreplace.searchreplaceutility, line 98, in searchObjects
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 5: ordinal not in range(128)

 - Expression: "context/@@searchreplacetable"
 - Filename:   ... y2.7.egg/collective/searchandreplace/browser/pageform.pt
 - Location:   (line 92: col 50)
 - Source:     ... replace="structure context/@@searchreplacetable" />
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "view/getItems"
 - Filename:   ... ollective/searchandreplace/browser/searchreplacetable.pt
 - Location:   (line 6: col 22)
 - Source:     items view/getItems;
                     ^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0xb35e7bacL>
               views: <ViewMapper - at 0xb052b68cL>
               modules: <instance - at 0xb6415decL>
               args: <tuple - at 0xb753d02cL>
               here: <ImplicitAcquisitionWrapper front-page at 0xb03e9d9cL>
               user: <ImplicitAcquisitionWrapper - at 0xb03e96bcL>
               view: <SimpleViewClass from /usr/local/Plone505test/buildout-cache/eggs/collective.searchandreplace-7.1-py2.7.egg/collective/searchandreplace/browser/searchreplacetable.pt searchreplacetable at 0xb052b10cL>
               nothing: <NoneType - at 0x83ac190>
               container: <ImplicitAcquisitionWrapper front-page at 0xb03e9d9cL>
               request: <instance - at 0xb102abecL>
               wrapped_repeat: <SafeMapping - at 0xb0dcc734L>
               traverse_subpath: <list - at 0xb102a48cL>
               default: <object - at 0xb7563700L>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0xb03e9d9cL>
               isFolderish: 0
               translate: <function translate at 0xb03e15a4L>
               root: <ImplicitAcquisitionWrapper Zope at 0xb0cc2eb4L>
               options: {...} (0)
               target_language: <NoneType - at 0x83ac190>
^C2016-07-24 00:03:36 INFO SignalHandler Caught signal SIGINT
2016-07-24 00:03:36 INFO Z2 Shutting down

**Comment by serge73** [comment]
same situation for version Plone 5.0.4

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module zope.formlib.form, line 800, in __call__
  Module zope.formlib.form, line 920, in render
  Module zope.formlib.form, line 790, in render
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 261, in render
  Module chameleon.template, line 171, in render
  Module bbdd25959ca055246654fd83c667d6ed.py, line 1699, in render
  Module c94341d518084cc5e15e52b738dab2e7.py, line 1223, in render_master
  Module c94341d518084cc5e15e52b738dab2e7.py, line 458, in render_content
  Module bbdd25959ca055246654fd83c667d6ed.py, line 1687, in __fill_main
  Module bbdd25959ca055246654fd83c667d6ed.py, line 1513, in render_form
  Module bbdd25959ca055246654fd83c667d6ed.py, line 531, in render_master
  Module five.pt.expressions, line 161, in __call__
  Module Products.Five.browser.metaconfigure, line 485, in __call__
  Module Products.Five.browser.pagetemplatefile, line 125, in __call__
  Module Products.Five.browser.pagetemplatefile, line 59, in __call__
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in __call__
  Module z3c.pt.pagetemplate, line 163, in render
  Module chameleon.zpt.template, line 261, in render
  Module chameleon.template, line 191, in render
  Module chameleon.template, line 171, in render
  Module 85f8ed32f55b3c3acf5536f4287f9ea6.py, line 121, in render
  Module five.pt.expressions, line 161, in __call__
  Module collective.searchandreplace.browser.searchreplacetable, line 40, in getItems
  Module collective.searchandreplace.searchreplaceutility, line 98, in searchObjects
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0401' in position 0: ordinal not in range(128)

 - Expression: "context/@@searchreplacetable"
 - Filename:   ... y2.7.egg/collective/searchandreplace/browser/pageform.pt
 - Location:   (line 92: col 50)
 - Source:     ... replace="structure context/@@searchreplacetable" />
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "view/getItems"
 - Filename:   ... ollective/searchandreplace/browser/searchreplacetable.pt
 - Location:   (line 6: col 22)
 - Source:     items view/getItems;
                     ^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0xb364820cL>
               views: <ViewMapper - at 0xb3479dacL>
               modules: <instance - at 0xb64055ccL>
               args: <tuple - at 0xb752802cL>
               here: <ImplicitAcquisitionWrapper front-page at 0xb10685ccL>
               user: <ImplicitAcquisitionWrapper - at 0xb10687acL>
               view: <SimpleViewClass from /usr/local/Plone504test/buildout-cache/eggs/collective.searchandreplace-7.1-py2.7.egg/collective/searchandreplace/browser/searchreplacetable.pt searchreplacetable at 0xb347990cL>
               nothing: <NoneType - at 0x83ac190>
               container: <ImplicitAcquisitionWrapper front-page at 0xb10685ccL>
               request: <instance - at 0xb145480cL>
               wrapped_repeat: <SafeMapping - at 0xb10438ecL>
               traverse_subpath: <list - at 0xb0f5850cL>
               default: <object - at 0xb754e700L>
               loop: {...} (0)
               context: <ImplicitAcquisitionWrapper front-page at 0xb10685ccL>
               isFolderish: 0
               translate: <function translate at 0xb323bd84L>
               root: <ImplicitAcquisitionWrapper Zope at 0xb3865cfcL>
               options: {...} (0)
               target_language: <NoneType - at 0x83ac190>

**Comment by mauritsvanrees** [comment]
I have released 7.1.1 with a fix.
